package com.example.androidtutorial_05;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    //This reference is generated by adding onClick tag in MainActivity.xml
    public void Click(View view) {

        Intent i = new Intent(getApplicationContext() ,second_activity.class);
        startActivity(i);

    }
}